/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InteriorDesignersCoimbatoreRouteImport } from './routes/interior-designers-coimbatore'
import { Route as HomeInteriorsCoimbatoreRouteImport } from './routes/home-interiors-coimbatore'
import { Route as ModularKitchenCoimbatoreRouteImport } from './routes/modular-kitchen-coimbatore'
import { Route as WardrobeDesignCoimbatoreRouteImport } from './routes/wardrobe-design-coimbatore'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorDesignersCoimbatoreRoute = InteriorDesignersCoimbatoreRouteImport.update({
  id: '/interior-designers-coimbatore',
  path: '/interior-designers-coimbatore',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeInteriorsCoimbatoreRoute = HomeInteriorsCoimbatoreRouteImport.update({
  id: '/home-interiors-coimbatore',
  path: '/home-interiors-coimbatore',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularKitchenCoimbatoreRoute = ModularKitchenCoimbatoreRouteImport.update({
  id: '/modular-kitchen-coimbatore',
  path: '/modular-kitchen-coimbatore',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeDesignCoimbatoreRoute = WardrobeDesignCoimbatoreRouteImport.update({
  id: '/wardrobe-design-coimbatore',
  path: '/wardrobe-design-coimbatore',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/interior-designers-coimbatore': typeof InteriorDesignersCoimbatoreRoute
  '/home-interiors-coimbatore': typeof HomeInteriorsCoimbatoreRoute
  '/modular-kitchen-coimbatore': typeof ModularKitchenCoimbatoreRoute
  '/wardrobe-design-coimbatore': typeof WardrobeDesignCoimbatoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/interior-designers-coimbatore': typeof InteriorDesignersCoimbatoreRoute
  '/home-interiors-coimbatore': typeof HomeInteriorsCoimbatoreRoute
  '/modular-kitchen-coimbatore': typeof ModularKitchenCoimbatoreRoute
  '/wardrobe-design-coimbatore': typeof WardrobeDesignCoimbatoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/interior-designers-coimbatore': typeof InteriorDesignersCoimbatoreRoute
  '/home-interiors-coimbatore': typeof HomeInteriorsCoimbatoreRoute
  '/modular-kitchen-coimbatore': typeof ModularKitchenCoimbatoreRoute
  '/wardrobe-design-coimbatore': typeof WardrobeDesignCoimbatoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/offers'
    | '/services'
    | '/sitemap.xml'
    | '/interior-designers-coimbatore'
    | '/home-interiors-coimbatore'
    | '/modular-kitchen-coimbatore'
    | '/wardrobe-design-coimbatore'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/offers'
    | '/services'
    | '/sitemap.xml'
    | '/interior-designers-coimbatore'
    | '/home-interiors-coimbatore'
    | '/modular-kitchen-coimbatore'
    | '/wardrobe-design-coimbatore'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/offers'
    | '/services'
    | '/sitemap.xml'
    | '/interior-designers-coimbatore'
    | '/home-interiors-coimbatore'
    | '/modular-kitchen-coimbatore'
    | '/wardrobe-design-coimbatore'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  OffersRoute: typeof OffersRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InteriorDesignersCoimbatoreRoute: typeof InteriorDesignersCoimbatoreRoute
  HomeInteriorsCoimbatoreRoute: typeof HomeInteriorsCoimbatoreRoute
  ModularKitchenCoimbatoreRoute: typeof ModularKitchenCoimbatoreRoute
  WardrobeDesignCoimbatoreRoute: typeof WardrobeDesignCoimbatoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-designers-coimbatore': {
      id: '/interior-designers-coimbatore'
      path: '/interior-designers-coimbatore'
      fullPath: '/interior-designers-coimbatore'
      preLoaderRoute: typeof InteriorDesignersCoimbatoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-interiors-coimbatore': {
      id: '/home-interiors-coimbatore'
      path: '/home-interiors-coimbatore'
      fullPath: '/home-interiors-coimbatore'
      preLoaderRoute: typeof HomeInteriorsCoimbatoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular-kitchen-coimbatore': {
      id: '/modular-kitchen-coimbatore'
      path: '/modular-kitchen-coimbatore'
      fullPath: '/modular-kitchen-coimbatore'
      preLoaderRoute: typeof ModularKitchenCoimbatoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe-design-coimbatore': {
      id: '/wardrobe-design-coimbatore'
      path: '/wardrobe-design-coimbatore'
      fullPath: '/wardrobe-design-coimbatore'
      preLoaderRoute: typeof WardrobeDesignCoimbatoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  OffersRoute: OffersRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InteriorDesignersCoimbatoreRoute: InteriorDesignersCoimbatoreRoute,
  HomeInteriorsCoimbatoreRoute: HomeInteriorsCoimbatoreRoute,
  ModularKitchenCoimbatoreRoute: ModularKitchenCoimbatoreRoute,
  WardrobeDesignCoimbatoreRoute: WardrobeDesignCoimbatoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
